// Generated by scripts/visual-scene/generate-contract-types.mjs.
// Source: configs/visual-scene/capability-registry.json. Do not edit by hand.

export const SCENE_PLAN_SCHEMA_VERSION = "1.0" as const;
export const CAPABILITY_REGISTRY_VERSION = "1.1.0" as const;

export const SCENE_ACTIONS = [
  "play_clip",
  "play_morph",
  "particle_flow",
  "signal_propagation",
  "highlight",
  "set_material_state",
  "fade",
  "show_label",
  "camera_focus",
  "camera_orbit",
  "wait"
] as const;

export const SCENE_TOPICS = [
  "cardiovascular_system",
  "general_anatomy"
] as const;

export const SCENE_ASSETS = [
  "heart.educational.v1",
  "circulation.major-vessels.v1"
] as const;

export const SEMANTIC_TARGETS = [
  "heart",
  "heart.right_atrium",
  "heart.right_ventricle",
  "heart.left_atrium",
  "heart.left_ventricle",
  "heart.tricuspid_valve",
  "heart.pulmonary_valve",
  "heart.mitral_valve",
  "heart.aortic_valve",
  "heart.vena_cavae",
  "heart.pulmonary_artery",
  "heart.pulmonary_veins",
  "heart.aorta",
  "circulation.pulmonary",
  "circulation.systemic",
  "camera.heart_overview",
  "camera.right_heart",
  "camera.left_heart"
] as const;

export const ANIMATION_CLIPS = [
  "normal_cardiac_cycle"
] as const;

export const ANIMATION_MORPHS = [
  "atrial_systole",
  "ventricular_systole"
] as const;

export const FLOW_PATHS = [
  "body_to_right_atrium",
  "right_atrium_to_right_ventricle",
  "right_ventricle_to_lungs",
  "lungs_to_left_atrium",
  "left_atrium_to_left_ventricle",
  "left_ventricle_to_body"
] as const;

export const SEMANTIC_STATES = [
  "default_tissue",
  "selected_structure",
  "oxygen_poor_blood",
  "oxygen_rich_blood"
] as const;

export const LABEL_TEXT_KEYS = [
  "heart.right_atrium",
  "heart.right_ventricle",
  "heart.left_atrium",
  "heart.left_ventricle",
  "heart.tricuspid_valve",
  "heart.pulmonary_valve",
  "heart.mitral_valve",
  "heart.aortic_valve"
] as const;

export const SCENE_VIEW_MODES = [
  "full_body",
  "skeleton",
  "muscular",
  "nervous_system",
  "circulatory",
  "respiratory",
  "digestive",
  "brain",
  "heart",
  "spine"
] as const;

export const SCENE_LIMITS = {
  "max_required_assets": 8,
  "max_tracks": 128,
  "max_steps": 64,
  "max_evidence_refs": 32
} as const;
export const TARGET_ASSETS = {
  "heart": "heart.educational.v1",
  "heart.right_atrium": "heart.educational.v1",
  "heart.right_ventricle": "heart.educational.v1",
  "heart.left_atrium": "heart.educational.v1",
  "heart.left_ventricle": "heart.educational.v1",
  "heart.tricuspid_valve": "heart.educational.v1",
  "heart.pulmonary_valve": "heart.educational.v1",
  "heart.mitral_valve": "heart.educational.v1",
  "heart.aortic_valve": "heart.educational.v1",
  "heart.vena_cavae": "heart.educational.v1",
  "heart.pulmonary_artery": "heart.educational.v1",
  "heart.pulmonary_veins": "heart.educational.v1",
  "heart.aorta": "heart.educational.v1",
  "circulation.pulmonary": "heart.educational.v1",
  "circulation.systemic": "heart.educational.v1"
} as const;
export const CLIP_TARGETS = {
  "normal_cardiac_cycle": [
    "heart"
  ]
} as const;
export const MORPH_TARGETS = {
  "atrial_systole": [
    "heart",
    "heart.right_atrium",
    "heart.left_atrium"
  ],
  "ventricular_systole": [
    "heart",
    "heart.right_ventricle",
    "heart.left_ventricle"
  ]
} as const;
export const FLOW_PATH_REQUIREMENTS = {
  "body_to_right_atrium": {
    "target": "circulation.systemic",
    "state": "oxygen_poor_blood",
    "required_assets": [
      "heart.educational.v1"
    ]
  },
  "right_atrium_to_right_ventricle": {
    "target": "heart",
    "state": "oxygen_poor_blood",
    "required_assets": [
      "heart.educational.v1"
    ]
  },
  "right_ventricle_to_lungs": {
    "target": "circulation.pulmonary",
    "state": "oxygen_poor_blood",
    "required_assets": [
      "heart.educational.v1"
    ]
  },
  "lungs_to_left_atrium": {
    "target": "circulation.pulmonary",
    "state": "oxygen_rich_blood",
    "required_assets": [
      "heart.educational.v1"
    ]
  },
  "left_atrium_to_left_ventricle": {
    "target": "heart",
    "state": "oxygen_rich_blood",
    "required_assets": [
      "heart.educational.v1"
    ]
  },
  "left_ventricle_to_body": {
    "target": "circulation.systemic",
    "state": "oxygen_rich_blood",
    "required_assets": [
      "heart.educational.v1"
    ]
  }
} as const;
export const CAMERA_TARGETS = [
  "camera.heart_overview",
  "camera.right_heart",
  "camera.left_heart"
] as const;

export const MATERIAL_TARGETS = [
  "heart",
  "heart.right_atrium",
  "heart.right_ventricle",
  "heart.left_atrium",
  "heart.left_ventricle",
  "heart.tricuspid_valve",
  "heart.pulmonary_valve",
  "heart.mitral_valve",
  "heart.aortic_valve",
  "heart.vena_cavae",
  "heart.pulmonary_artery",
  "heart.pulmonary_veins",
  "heart.aorta",
  "circulation.pulmonary",
  "circulation.systemic"
] as const;

export const CONFLICT_GROUPS = {
  "material_state": [
    "highlight",
    "set_material_state",
    "fade"
  ],
  "camera_motion": [
    "camera_focus",
    "camera_orbit"
  ]
} as const;

export type SceneAction = (typeof SCENE_ACTIONS)[number];
export type SceneTopic = (typeof SCENE_TOPICS)[number];
export type SceneAssetId = (typeof SCENE_ASSETS)[number];
export type SemanticTarget = (typeof SEMANTIC_TARGETS)[number];
export type AnimationClip = (typeof ANIMATION_CLIPS)[number];
export type AnimationMorph = (typeof ANIMATION_MORPHS)[number];
export type FlowPath = (typeof FLOW_PATHS)[number];
export type SemanticState = (typeof SEMANTIC_STATES)[number];
export type LabelTextKey = (typeof LABEL_TEXT_KEYS)[number];
export type SceneViewMode = (typeof SCENE_VIEW_MODES)[number];
export type CameraTarget = (typeof CAMERA_TARGETS)[number];
export type MaterialTarget = (typeof MATERIAL_TARGETS)[number];

type TrackBase<
  TAction extends SceneAction,
  TTarget extends SemanticTarget = SemanticTarget
> = {
  id: string;
  target: TTarget;
  action: TAction;
  start_ms: number;
  duration_ms: number;
};

export type PlayClipTrack = {
  [TClip in AnimationClip]: TrackBase<
    "play_clip",
    (typeof CLIP_TARGETS)[TClip][number]
  > & {
    clip: TClip;
    loop: boolean;
  };
}[AnimationClip];

export type PlayMorphTrack = {
  [TMorph in AnimationMorph]: TrackBase<
    "play_morph",
    (typeof MORPH_TARGETS)[TMorph][number]
  > & {
    morph: TMorph;
    from: number;
    to: number;
  };
}[AnimationMorph];

export type FlowTrack = {
  [TPath in FlowPath]: TrackBase<
    "particle_flow" | "signal_propagation",
    (typeof FLOW_PATH_REQUIREMENTS)[TPath]["target"]
  > & {
    path: TPath;
    state: (typeof FLOW_PATH_REQUIREMENTS)[TPath]["state"];
  };
}[FlowPath];

export type MaterialTrack = TrackBase<
  "highlight" | "set_material_state",
  MaterialTarget
> & {
  state: SemanticState;
};

export type FadeTrack = TrackBase<"fade", MaterialTarget> & {
  opacity: number;
};

export type LabelTrack = {
  [TTextKey in LabelTextKey]: TrackBase<"show_label", TTextKey> & {
    text_key: TTextKey;
  };
}[LabelTextKey];

export type CameraTrack = TrackBase<
  "camera_focus" | "camera_orbit",
  CameraTarget
>;
export type WaitTrack = TrackBase<"wait">;

export type SceneTrack =
  | PlayClipTrack
  | PlayMorphTrack
  | FlowTrack
  | MaterialTrack
  | FadeTrack
  | LabelTrack
  | CameraTrack
  | WaitTrack;

export type SceneStep = {
  id: string;
  start_ms: number;
  end_ms: number;
  caption: string;
};

export type SceneFallback = {
  view_mode: SceneViewMode;
  message: string;
};

export type ScenePlan = {
  schema_version: typeof SCENE_PLAN_SCHEMA_VERSION;
  capability_registry_version: typeof CAPABILITY_REGISTRY_VERSION;
  plan_id: string;
  topic: SceneTopic;
  learning_objective: string;
  duration_ms: number;
  loop: boolean;
  required_assets: SceneAssetId[];
  tracks: SceneTrack[];
  steps: SceneStep[];
  evidence_refs: string[];
  fallback: SceneFallback;
};
